<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718082209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attivita (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(255) NOT NULL, titolo VARCHAR(200) NOT NULL, descrizione TEXT DEFAULT NULL, data_scadenza TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completata BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lead_id INT NOT NULL, assegnatario_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D61334C55458D ON attivita (lead_id)');
        $this->addSql('CREATE INDEX IDX_1D61334CDD58B805 ON attivita (assegnatario_id)');
        $this->addSql('CREATE TABLE campagna (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(150) NOT NULL, fonte VARCHAR(255) NOT NULL, attiva BOOLEAN NOT NULL, budget NUMERIC(12, 2) DEFAULT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(100) NOT NULL, cognome VARCHAR(100) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, telefono VARCHAR(40) DEFAULT NULL, codice_fiscale VARCHAR(20) DEFAULT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lead (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(100) NOT NULL, cognome VARCHAR(100) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, telefono VARCHAR(40) DEFAULT NULL, fonte VARCHAR(255) NOT NULL, stato VARCHAR(255) NOT NULL, destinazione VARCHAR(150) DEFAULT NULL, periodo VARCHAR(100) DEFAULT NULL, numero_passeggeri INT DEFAULT NULL, budget_indicativo NUMERIC(12, 2) DEFAULT NULL, note TEXT DEFAULT NULL, consenso_marketing BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, campagna_id INT DEFAULT NULL, assegnatario_id INT DEFAULT NULL, cliente_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_289161CB9940E423 ON lead (campagna_id)');
        $this->addSql('CREATE INDEX IDX_289161CBDD58B805 ON lead (assegnatario_id)');
        $this->addSql('CREATE INDEX IDX_289161CBDE734E51 ON lead (cliente_id)');
        $this->addSql('CREATE INDEX idx_lead_stato ON lead (stato)');
        $this->addSql('CREATE TABLE preventivo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(30) NOT NULL, titolo VARCHAR(200) NOT NULL, stato VARCHAR(255) NOT NULL, valido_fino DATE DEFAULT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lead_id INT DEFAULT NULL, cliente_id INT DEFAULT NULL, creato_da_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A52D7F6B55458D ON preventivo (lead_id)');
        $this->addSql('CREATE INDEX IDX_A52D7F6BDE734E51 ON preventivo (cliente_id)');
        $this->addSql('CREATE INDEX IDX_A52D7F6B20958DFB ON preventivo (creato_da_id)');
        $this->addSql('CREATE TABLE scenario_preventivo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(120) NOT NULL, descrizione TEXT DEFAULT NULL, consigliato BOOLEAN NOT NULL, markup_percentuale NUMERIC(5, 2) NOT NULL, ordinamento INT NOT NULL, preventivo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1CD0CFBFCFBBD818 ON scenario_preventivo (preventivo_id)');
        $this->addSql('CREATE TABLE utente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nome VARCHAR(100) NOT NULL, cognome VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON utente (email)');
        $this->addSql('CREATE TABLE voce_costo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, categoria VARCHAR(255) NOT NULL, descrizione VARCHAR(200) NOT NULL, quantita INT NOT NULL, costo_unitario NUMERIC(12, 2) NOT NULL, ordinamento INT NOT NULL, scenario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C0B511EE04E49DF ON voce_costo (scenario_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE attivita ADD CONSTRAINT FK_1D61334C55458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attivita ADD CONSTRAINT FK_1D61334CDD58B805 FOREIGN KEY (assegnatario_id) REFERENCES utente (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CB9940E423 FOREIGN KEY (campagna_id) REFERENCES campagna (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CBDD58B805 FOREIGN KEY (assegnatario_id) REFERENCES utente (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CBDE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE preventivo ADD CONSTRAINT FK_A52D7F6B55458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE preventivo ADD CONSTRAINT FK_A52D7F6BDE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE preventivo ADD CONSTRAINT FK_A52D7F6B20958DFB FOREIGN KEY (creato_da_id) REFERENCES utente (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scenario_preventivo ADD CONSTRAINT FK_1CD0CFBFCFBBD818 FOREIGN KEY (preventivo_id) REFERENCES preventivo (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE voce_costo ADD CONSTRAINT FK_9C0B511EE04E49DF FOREIGN KEY (scenario_id) REFERENCES scenario_preventivo (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attivita DROP CONSTRAINT FK_1D61334C55458D');
        $this->addSql('ALTER TABLE attivita DROP CONSTRAINT FK_1D61334CDD58B805');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CB9940E423');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CBDD58B805');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CBDE734E51');
        $this->addSql('ALTER TABLE preventivo DROP CONSTRAINT FK_A52D7F6B55458D');
        $this->addSql('ALTER TABLE preventivo DROP CONSTRAINT FK_A52D7F6BDE734E51');
        $this->addSql('ALTER TABLE preventivo DROP CONSTRAINT FK_A52D7F6B20958DFB');
        $this->addSql('ALTER TABLE scenario_preventivo DROP CONSTRAINT FK_1CD0CFBFCFBBD818');
        $this->addSql('ALTER TABLE voce_costo DROP CONSTRAINT FK_9C0B511EE04E49DF');
        $this->addSql('DROP TABLE attivita');
        $this->addSql('DROP TABLE campagna');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE lead');
        $this->addSql('DROP TABLE preventivo');
        $this->addSql('DROP TABLE scenario_preventivo');
        $this->addSql('DROP TABLE utente');
        $this->addSql('DROP TABLE voce_costo');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
