<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718152726 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE google_calendar_collegamento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token JSON NOT NULL, calendar_id VARCHAR(200) NOT NULL, sync_token TEXT DEFAULT NULL, attivo BOOLEAN NOT NULL, collegato_il TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utente_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_80C93F66FD5D2A ON google_calendar_collegamento (utente_id)');
        $this->addSql('ALTER TABLE google_calendar_collegamento ADD CONSTRAINT FK_80C93F66FD5D2A FOREIGN KEY (utente_id) REFERENCES utente (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attivita ADD google_event_id VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE google_calendar_collegamento DROP CONSTRAINT FK_80C93F66FD5D2A');
        $this->addSql('DROP TABLE google_calendar_collegamento');
        $this->addSql('ALTER TABLE attivita DROP google_event_id');
    }
}
