<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260921132934 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversazione (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, canale VARCHAR(255) NOT NULL, id_esterno VARCHAR(64) NOT NULL, nome VARCHAR(150) DEFAULT NULL, telefono VARCHAR(40) DEFAULT NULL, non_letti INT DEFAULT 0 NOT NULL, anteprima VARCHAR(255) DEFAULT NULL, ultimo_messaggio_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lead_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_89B610C155458D ON conversazione (lead_id)');
        $this->addSql('CREATE INDEX idx_conv_ultimo ON conversazione (ultimo_messaggio_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_conv_canale_esterno ON conversazione (canale, id_esterno)');
        $this->addSql('CREATE TABLE messaggio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, direzione VARCHAR(255) NOT NULL, testo TEXT NOT NULL, tipo VARCHAR(20) DEFAULT \'text\' NOT NULL, id_esterno VARCHAR(128) DEFAULT NULL, stato VARCHAR(20) DEFAULT NULL, errore TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversazione_id INT NOT NULL, autore_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A511899E9EEC3D26 ON messaggio (conversazione_id)');
        $this->addSql('CREATE INDEX IDX_A511899EBECEFFB6 ON messaggio (autore_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_msg_id_esterno ON messaggio (id_esterno)');
        $this->addSql('ALTER TABLE conversazione ADD CONSTRAINT FK_89B610C155458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messaggio ADD CONSTRAINT FK_A511899E9EEC3D26 FOREIGN KEY (conversazione_id) REFERENCES conversazione (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messaggio ADD CONSTRAINT FK_A511899EBECEFFB6 FOREIGN KEY (autore_id) REFERENCES utente (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversazione DROP CONSTRAINT FK_89B610C155458D');
        $this->addSql('ALTER TABLE messaggio DROP CONSTRAINT FK_A511899E9EEC3D26');
        $this->addSql('ALTER TABLE messaggio DROP CONSTRAINT FK_A511899EBECEFFB6');
        $this->addSql('DROP TABLE conversazione');
        $this->addSql('DROP TABLE messaggio');
    }
}
