<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260914153033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tema (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(150) NOT NULL, immagine VARCHAR(255) DEFAULT NULL, descrizione TEXT DEFAULT NULL, fotografo VARCHAR(150) DEFAULT NULL, fotografo_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tipologia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(150) NOT NULL, immagine VARCHAR(255) DEFAULT NULL, descrizione TEXT DEFAULT NULL, fotografo VARCHAR(150) DEFAULT NULL, fotografo_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE tema');
        $this->addSql('DROP TABLE tipologia');
    }
}
