<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718142732 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE regola_nurturing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stato VARCHAR(255) NOT NULL, tipo VARCHAR(255) NOT NULL, titolo VARCHAR(200) NOT NULL, giorni_offset INT NOT NULL, ordinamento INT NOT NULL, attiva BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE attivita ADD automatica BOOLEAN DEFAULT FALSE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE regola_nurturing');
        $this->addSql('ALTER TABLE attivita DROP automatica');
    }
}
