<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260720082744 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE offerta (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titolo VARCHAR(180) NOT NULL, sottotitolo VARCHAR(200) DEFAULT NULL, descrizione TEXT DEFAULT NULL, prezzo_da NUMERIC(12, 2) DEFAULT NULL, durata VARCHAR(100) DEFAULT NULL, valido_dal DATE DEFAULT NULL, valido_al DATE DEFAULT NULL, attiva BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, destinazione_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_226DBEBF1D48AA5 ON offerta (destinazione_id)');
        $this->addSql('ALTER TABLE offerta ADD CONSTRAINT FK_226DBEBF1D48AA5 FOREIGN KEY (destinazione_id) REFERENCES destinazione (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE offerta DROP CONSTRAINT FK_226DBEBF1D48AA5');
        $this->addSql('DROP TABLE offerta');
    }
}
