<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718154535 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE destinazione (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(150) NOT NULL, immagine VARCHAR(255) DEFAULT NULL, descrizione TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tappa_viaggio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titolo VARCHAR(200) NOT NULL, descrizione TEXT DEFAULT NULL, giorno INT DEFAULT NULL, ordinamento INT NOT NULL, preventivo_id INT NOT NULL, destinazione_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8FF18857CFBBD818 ON tappa_viaggio (preventivo_id)');
        $this->addSql('CREATE INDEX IDX_8FF18857F1D48AA5 ON tappa_viaggio (destinazione_id)');
        $this->addSql('ALTER TABLE tappa_viaggio ADD CONSTRAINT FK_8FF18857CFBBD818 FOREIGN KEY (preventivo_id) REFERENCES preventivo (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tappa_viaggio ADD CONSTRAINT FK_8FF18857F1D48AA5 FOREIGN KEY (destinazione_id) REFERENCES destinazione (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tappa_viaggio DROP CONSTRAINT FK_8FF18857CFBBD818');
        $this->addSql('ALTER TABLE tappa_viaggio DROP CONSTRAINT FK_8FF18857F1D48AA5');
        $this->addSql('DROP TABLE destinazione');
        $this->addSql('DROP TABLE tappa_viaggio');
    }
}
